# theme.toml template for a Hugo theme

name = "minwtShop"
description = "這是梅問題購物，採用hugo建製"
homepage = "https://www.minwnt.com.tw"
tags = []
features = []
min_version = "0.3"

[author]
  name = "minwt"
  homepage = "https://www.minwnt.com/"
